Module2 task1
htmlacademy-javascript/2314313-kekstagram-28 pull request #2
Opened 2023-02-22 19:07 UTC by Angelinaandr

2023-02-27 10:54 UTC, Oleg979 requested changes

2023-02-27 10:54 UTC, Oleg979 commented on js/functions.js
> +  if (sentence.length === symbolsAmount) {
`Она принимает строку, которую нужно проверить, и максимальную длину и возвращает true, если строка меньше или равна указанной длине, и false, если строка длиннее`
Надо чуток доработать, чтобы соответствовало условию

2023-02-27 10:54 UTC, Oleg979 commented on js/functions.js
> +  for (let i = 0; i < wordForCheck.length; i++) {
Немного перегруженный фор. Давай будем цикл вести с последнего символа и делать i--. Так будет гораздо читабельнее и понятнее, что ты хочешь сделать

2023-02-27 10:54 UTC, Oleg979 commented on js/functions.js
> +function extractNumber(string) {
extractNumber(123) не будет работать. Давай починим

2023-02-27 10:54 UTC, Oleg979 commented on js/functions.js
> +  if (originalString.length >= minLength) {
Строчкой выше ты уже посчитала difference. Так что нет нужды опять сравнивать две этих переменных. Ты можешь сделать иф по значению difference

2023-03-02 15:36 UTC, Angelinaandr commented
Недочеты исправила.

2023-03-06 07:42 UTC, Oleg979 commented on js/functions.js
> +  const string = String(maybeString);
Вообще по-хорошему, если нам пришло число, то мы не хотим превращать его в строку и делать по ней цикл, чтобы получить снова это же число. Мы хотим просто его отдать как есть. Но технически ты починила и так тоже будет работать.

2023-03-06 07:43 UTC, merged